name: maven build publish
run-name: build triggered by ${{ github.actor }}
on: [push]
jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: |
          mvn clean install
          ls
          ls target
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to jfrog
        uses: docker/login@v3
        with:
          registry: monishreg.jfrog.io
          username: admin 
          password: A^#c%vgTRtjuL9
      - name: build and push docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: monishreg.jfrog.io/test:latest
